var d = document
var logincode;
var myxyzyhyghyy
if (window.location.search == "?chkkey") {
  if (EnterYourkey == key) {

  }
  else {
    location.href = 'key-error.html'
  }
}
if (window.location.search == "?open") {

  $(document).ready(function () {
    $("#exampleModal").modal('show');
    // $("#modalt").addClass( "modal-dialog modal-lg" );
    $("#f").addClass("hide");
    window.onload = function hev() {
      if (d.getElementById("g").style.display = "block") { d.getElementById("g").style.display = "none" }
      return true

    }
    d.getElementById("analyticname").innerHTML = localStorage.getItem("pointsname")
    d.getElementById("analyticname").title = "Username: " + localStorage.getItem("pointsname")
    d.getElementById("passname").innerHTML = logincode
    d.getElementById("passname").title = "Password: " + logincode
    d.getElementById("dhujtjtfhyf").style.display = "block"
    document.getElementById("myhellclose").style.display = "none"
    document.getElementById("myhellclosed").style.display = "block"
    document.getElementById("myidop").style.display = "none"
    document.getElementById("myidopp").style.display = "block"
    d.getElementById("chair1").style.display = "none"
    d.getElementById("chair2").style.display = "none"
    d.getElementById("chair3").style.display = "none"

    document.title = "Analytics/Information"
  });
}
